### ISSUE TITLE
Blog post announcing charter arrangement

### ISSUE THREAD

**Issue by jessbeutler** [osmus/osmcha-charter-project#4]
- [x] Required: OSM US blogpost announcing charter project
- [x] Optional: additional blog post on personal or project blog

**Comment by jessbeutler** [comment]
[Blog post on OpenStreetMap US website on Feb 17](https://www.openstreetmap.us/2023/02/osmcha_announcement)

**Comment by willemarcel** [comment]
[Blog post on my OSM Diary](https://www.openstreetmap.org/user/wille/diary/401146)

We are planning to make another post in the DevSeed blog when we finish the migration work.

**Comment by jessbeutler** [comment]
I'll keep this open until the DevSeed post.

**Comment by jake-low** [comment]
Closing this. Migration work has been complete for a while, though I'm not sure if a post was made announcing this.

**Comment by kcarini** [comment]
@jake-low here is our [post](https://developmentseed.org/blog/2024-06-04-osmcha/).

**Comment by jake-low** [comment]
Awesome, thanks for the link!
