### ISSUE TITLE
Update OSM Wiki pages

### ISSUE THREAD

**Issue by jessbeutler** [osmus/osmcha-charter-project#7]
Update OSM Wiki pages to reflect your charter status:
- [x] [OSM Cha page](https://wiki.openstreetmap.org/wiki/OSMCha) 
- [x] [OpenStreetMap US](https://wiki.openstreetmap.org/wiki/Foundation/Local_Chapters/United_States#Charter_Projects) page.

**Comment by jessbeutler** [comment]
Already completed by @1ec5 (thank you!)

**Comment by 1ec5** [comment]
[Also updated Wikidata](https://www.wikidata.org/wiki/Special:Diff/1836282672). 🤓
