### ISSUE TITLE
Adopt and share the OpenStreetMap US Code of Conduct

### ISSUE THREAD

**Issue by jessbeutler** [osmus/osmcha-charter-project#8]
As an OpenStreetMap US Charter Project, you’ve agreed to adopt our [Code of Conduct](https://wiki.openstreetmap.org/wiki/Foundation/Local_Chapters/United_States/Code_of_Conduct_Committee/OSM_US_Code_of_Conduct) for your project. As part of this, you will need to:

- [ ] Share and review the Code of Conduct among the Advisory Board making sure everyone understands the terms and knows how to report issues.

- [ ] Add the link to our Code of Conduct to your website, github, OSM wiki, and/or other areas where contributors and users will interact with the project.

**Comment by willemarcel** [comment]
I've added the code of conduct to the repositories that are not hosted by Mapbox, like:
https://github.com/osmlab/changeset-map/
https://github.com/willemarcel/osmcha-django
https://github.com/willemarcel/osmcha

I believe it's better to switch to the OSM US CoC after we finish the migration from Mapbox infrastructure or at least have a concrete plan around it.

**Comment by jessbeutler** [comment]
Hey Wille - that makes sense, we can pause further work on this task until the migration is complete.

**Comment by jake-low** [comment]
The main repositories for this project (listed below) all link to the OSM US CoC now, so I think this issue can be closed.

- https://github.com/OSMCha/osmcha-frontend
- https://github.com/OSMCha/osmcha-django
- https://github.com/OSMCha/osmcha
- https://github.com/osmlab/changeset-map/
